services:
    web:
      build: .
      command: python /code/manage.py runserver 0.0.0.0:8000
      volumes:
       - .:/code
      ports:
       - 8000:8000
      depends_on:
       - 'postgres_db'
      environment:
       - SECRET_KEY=${PROJECT_SECRET_KEY}
       - DEBUG=${PROJECT_DEBUG}
    